name: "Daily Snowy Spider Crawl"

# Trigger everyday at midnight
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the spider
      - name: Run Snowy spider
        working-directory: ./project2
        run: |
          scrapy crawl snowy \
            -o output_files/results.json

      # Debug: list the output directory
      - name: List output files
        run: ls -R project2/output_files

      # 5. Commit & push the output
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🕷️ Daily snowy crawl results"
          file_pattern: "project2/output_files/*.json"
          skip_dirty_check: true

      # Save results.json as an artifact as a backup
      - name: Upload results.json
        uses: actions/upload-artifact@v4
        with:
          name: snowy-results
          path: project2/output_files/results.json
